constexpr auto CONCAT(LIBRARY_NAME, COUNTER_A) = Append(CONCAT(LIBRARY_NAME, COUNTER_B), (SQ_FUNCTION_CLS_NAME_EXPAND(SQ_FUNCTION())(&SQ_FUNCTION_CLSNAME(SQ_FUNCTION()))), STRINGG(SQ_FUNCTION_NAME(SQ_FUNCTION())));
#include INCREMENT_COUNTER_A
#include INCREMENT_COUNTER_B